# Generated by Django 3.2 on 2023-01-21 09:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_favourites"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("newmanager", django.db.models.manager.Manager()),
            ],
        ),
    ]
