# Generated by Django 3.2 on 2023-01-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20230121_1216"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="review",
            name="email",
        ),
        migrations.RemoveField(
            model_name="review",
            name="name",
        ),
    ]
