# Generated by Django 3.2 on 2023-01-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_auto_20230121_1244"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="rating",
        ),
    ]
