# Generated by Django 3.2 on 2023-01-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
