# Generated by Django 3.2 on 2023-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_product_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(default=3),
        ),
    ]
