# Generated by Django 3.2 on 2023-01-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20230122_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(default='false', max_length=254),
        ),
    ]
