# Generated by Django 3.2 on 2023-01-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_review_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(default='user.username', max_length=254),
        ),
    ]
